### ISSUE TITLE
Create a mock server app inside a Nx monorepo

### ISSUE THREAD

**Issue by ng-plex** [mocks-server/main#293]
**Is your feature request related to a problem? Please describe.**
I would like to add the mock server to an Nx monorepo which includes some apps and libs. I would like to add as a new app then using the `main.ts` file I would like to start the mocksServer. I found a way using the MocksServer Core dependency, but also found it is archived. It is possible to access through the `@mocks-server/main` internal package?

```
const { Core } = require("@mocks-server/core");
const AdminApi = require("@mocks-server/plugin-admin-api");
const InquirerCli = require("@mocks-server/plugin-inquirer-cli");

const mocksServer = new Core({
  onlyProgrammaticOptions: false,
  plugins: [AdminApi, InquirerCli]
});

mocksServer
  .init({
    port: 3500,
    delay: 1000,
    log: "debug"
  })
  .then(server.start);
```

**Describe the solution you'd like**
Ability to use a Nx typescript based project in order to integrate into the Nx monorepo project. Could be a better approach to do it?

**Comment by javierbrea** [comment]
Hi @ng-plex,
Yes, you can use it. In fact, this repository itself is a monorepo built with Nx, and it starts some MockServer applications using the `@mocks-server/main` package in order to run some E2E tests 😃 

You can check it in the folders `mocks/admin-api-client-unit-mocks` and `mocks/admin-api-client-data-provider-e2e-mocks`.

I think that maybe the point here is not to use a Nx TypeScript based project, because the `@mocks-server/main` package already provides an executable. In my case, I am using the default Nx task runner for executing a script from the MockServer project's `package.json`. For example, if your MocksServer project contains a `start` script that run the server, you could do `pnpm nx start admin-api-client-unit-mocks`.
When I want to start the server for running other project E2E tests as part of the pipeline, then I call to that command from a script in the desired project. You have an example of this in [this `package.json` file](https://github.com/mocks-server/main/blob/master/test/admin-api-client-data-provider-react-app-e2e/package.json). In that example you'll also see that I use `start-server-and-test` to wait for the server before start running the tests.

**Comment by ng-plex** [comment]
Hi @javierbrea thanks so much for your quick reply, I will review it and give you some feedback as soon as possible.

**Comment by javierbrea** [comment]
Hi again @ng-plex ,

From version 3.0.0 you can also import the Core dependency using the `@mocks-server/main` package.

It also provides a `createServer` method for creating core instances including all plugins preinstalled in the main distribution (but note that it modifies the default configuration in order to optimize it for a programmatic usage, so files are not loaded and routes should be loaded programmatically. Anyway, you could change the configuration at your convenience because it accepts configuration as a parameter). For further info you can [checkout the API docs](https://www.mocks-server.org/docs/api/javascript).
