### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by vikramatcoupa** [mocks-server/main#434]
**Describe the bug**
Despite enabling the https specific configuration, the URL is not https.

**To Reproduce**

- Copied localhost.crt and localhost.key files to the root path. 
- Content of mock.config.js

```
module.exports = {
  mocks: {
    selected: "base",
  },
  server: {
    https: {
      enabled: true,
      cert: "localhost.crt",
      key: "localhost.key",
    },
  },
};

```

**Expected behavior**
Mock server should be hosted on https://localhost:3100

** Actual **
Mock server started on http://localhost:3100

**Logs**
If applicable, add logs to help explain your problem.

 - OS: MacOS
 - Node.js: v15.3.0
 - npm: v7.0.14

Thanks for the help in advance.

**Comment by javierbrea** [comment]
Hi @vikramatcoupa , which version of @mocks-server/main are you using?
Could you please server logs? Is there any reference to some error loading the https config?

**Comment by javierbrea** [comment]
@vikramatcoupa I have tested your config in MacOS with Node.js v15.3.0 and it works as expected. HTTPS is working with:
* OS: MacOS
* Node.js: v15
* `@mocks-server/main`: 3.11.0

In fact, you can ignore my previous comment, because I have checked that the server fails to start when an invalid HTTPs certificate is provided,  it never fallbacks to start the server using HTTP instead of HTTPS when HTTPS is enabled. So, maybe you should ensure that your configuration file is being loaded properly, for example. You could:
* Check your applied configuration setting the "log" level to "silly" and disabling the interactive CLI in order to let logs being printed (`mocks-server --log=silly --no-plugins.inquirerCli.enabled`). Then you can check the applied configuration in logs.
* Check your applied configuration using the adminApi config endpoint once the server is started (`curl http://localhost:3110/api/config`)

If you don't find the problem, then you could also provide a reproducible example in a Github repository.

**Comment by vikramatcoupa** [comment]
Thanks @javierbrea  for your response. When I tried as cli commands from package.json file, it started working for me too. thats when I figured out an issue with my config file and fixed it.
